# decoration 负责窗口装饰绘制
# vswitch 工作区切换
# expo 工作区预览
# grid 网格工作区
[core]
plugins = autostart \
          command \
          scale \
          move \
          resize \
          switcher \
          wm-actions \
          place \
          grid \
          decoration \
          expo \
          zoom \
          idle \
          vswitch \
          input-method-v1 \
          wayfire-shell \
          xdg-activation \
          ipc \
          ipc-rules foreign-toplevel session-lock


close_top_view = <super> KEY_C

vwidth = 2
vheight = 2

# Prefer client-side decoration or server-side decoration
preferred_decoration_mode = server

xwayland = true

[input]
natural_scroll = true
kb_numlock_default_state = true
disable_touchpad_while_typing = true
disable_touchpad_while_mouse = true

[autostart]
0_env = dbus-update-activation-environment --systemd WAYLAND_DISPLAY DISPLAY XAUTHORITY WAYFIRE_SOCKET XDG_CURRENT_DESKTOP=wayfire
fcitx5 = fcitx5 -d -r
# screenshot = flameshot
nm-applet = nm-applet
polkit = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

autostart_wf_shell = false

# Set the wallpaper, start a panel and dock if you want one.
# https://github.com/WayfireWM/wf-shell
#
# These are started by the autostart_wf_shell option above.
#
background = wf-background
panel = ~/.config/wayfire/wf-panel-watchdog.sh
#
# You may also use wf-dock,
# which is included in wf-shell but is not enabled by default.
#
# dock = wf-dock

# Output configuration
# https://wayland.emersion.fr/kanshi/
# outputs = kanshi

# Notifications
# https://wayland.emersion.fr/mako/
notifications = mako

# Screen color temperature
# https://sr.ht/~kennylevinsen/wlsunset/
# gamma = wlsunset

# idle = swayidle -w timeout 480 'wf-locker' before-sleep 'pkill wf-locker; sleep 0.5' after-resume 'sleep 0.1; wf-locker'
idle = swayidle -w timeout 480 'wf-locker' after-resume 'pkill wf-locker; wf-locker'
# idle = swayidle before-sleep 'wf-locker'

# XDG desktop portal
# Needed by some GTK applications
# portal = /usr/lib/xdg-desktop-portal-wlr

xdp = sleep 1 && systemctl --user restart xdg-desktop-portal xdg-desktop-portal-wlr

[command]

# Start a terminal
# https://github.com/alacritty/alacritty
binding_terminal = <super> KEY_ENTER
command_terminal = foot

# Screen locker
binding_lock = <super> KEY_M
command_lock = wf-locker

# Screenshots
# https://wayland.emersion.fr/grim/
# https://wayland.emersion.fr/slurp/
# binding_screenshot = KEY_PRINT
# command_screenshot = grim $(date '+%F_%T').webp
# binding_screenshot_interactive = <shift> KEY_PRINT
# command_screenshot_interactive = slurp | grim -g - $(date '+%F_%T').webp

# Volume controls
# https://alsa-project.org
repeatable_binding_volume_up = KEY_VOLUMEUP
command_volume_up = amixer set Master 5%+
repeatable_binding_volume_down = KEY_VOLUMEDOWN
command_volume_down = amixer set Master 5%-
binding_mute = KEY_MUTE
command_mute = amixer set Master toggle

# Screen brightness
# https://haikarainen.github.io/light/
repeatable_binding_light_up = KEY_BRIGHTNESSUP
command_light_up = light -A 5
repeatable_binding_light_down = KEY_BRIGHTNESSDOWN
command_light_down = light -U 5

[scale]
toggle = <super> KEY_TAB
toggle_all = <super> KEY_A
spacing = 15

[move]
activate = <super> BTN_LEFT

[resize]
activate = <super> BTN_RIGHT

[switcher]
next_view = <alt> KEY_TAB
prev_view = <alt> <shift> KEY_TAB
speed = 300
view_thumbnail_scale = 1.5

[wm-actions]
toggle_fullscreen = <super> <shift> KEY_F
toggle_maximize = <super> KEY_F
toggle_showdesktop = <super> KEY_D


[place]
# 新窗口位置 居中(center)、cascade、随机(random)
mode = random

[decoration]
active_color = 0.2 0.4 1 1
inactive_color = 0.3 0.3 0.3 1
border_size = 2
title_height = 0

[expo]
toggle = <super>
# select_workspace_1 = <super> KEY_1

# 缩放
[zoom]
modifier = <alt>

[idle]
dpms_timeout = 600

[vswitch]
binding_down = <super> KEY_J
binding_left = <super> KEY_H
binding_right = <super> KEY_L
binding_up = <super> KEY_K
binding_1 = <super> KEY_1
binding_2 = <super> KEY_2
binding_3 = <super> KEY_3
binding_4 = <super> KEY_4
with_win_1 = <super> <shift> KEY_1
with_win_2 = <super> <shift> KEY_2
with_win_3 = <super> <shift> KEY_3
with_win_4 = <super> <shift> KEY_4

[workarounds]
app_id_mode = full
use_external_output_configuration = false

[wayfire-shell]
toggle_menu = <super> KEY_P

[window-rules]

[xdg-activation]
check_surface = true
