name: 监控上游仓库更新（每日晚6点）

on:
  schedule:
    - cron: "0 10 * * *"
  workflow_dispatch:

permissions:
  contents: write
  issues: write

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - uses: actions/setup-go@v7
        with:
          go-version: '1.26'
          cache: false

      - name: run go
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            cd .github
            go run procedure/watch-pkg-version/watch-repo.go

      - name: Check for changes
        run: |
          if [ -z "$(if [ -z "$(git status --porcelain)" ]; then)" ]; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit files
        if: steps.check.outputs.changed == 'true'
        run: |
          git config --local user.email "a3427173515@163.com"
          git config --local user.name "roukaixin"
          git commit -a -m "update package version"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
